NB_OF_CATEGORY_TO_SHOW = 50
NB_OF_PRODUCT_TO_SHOW = 50
NB_OF_SUBSTITUTE_TO_SHOW = 50
NB_OF_FAVORITE_SUBSTITUTE_TO_SHOW = 50

DATABASE_HOST = "localhost"
DATABASE_NAME = "open_food_fact"
DATABASE_USER = "root"
DATABASE_PWD = "arnaud06"
DATABASE_ACCESS_PORT = "3307"

PLAIN_TEXT_BACKGROUND_COLOR = "03,03,03"
