NB_OF_CATEGORY_TO_SHOW = 50
NB_OF_PRODUCT_TO_SHOW = 50
NB_OF_SUBSTITUTE_TO_SHOW = 50
NB_OF_FAVORITE_SUBSTITUTE_TO_SHOW = 50

DATABASE_HOST = "host"
DATABASE_NAME = "database_name"
DATABASE_USER = "user"
DATABASE_PWD = "password"
DATABASE_ACCESS_PORT = "port"

PLAIN_TEXT_BACKGROUND_COLOR = "03,03,03"
